import type { MetricValue, TrialDetail } from '../api/types'

export function metric(overrides: Partial<MetricValue> = {}): MetricValue {
  return {
    name: 'observed_pass_rate',
    definition_version: 'observed_pass_rate@1',
    score_type: 'observed_rate',
    value: 0.9,
    unit: 'fraction of graded repeats',
    direction: 'higher_is_better',
    numerator: 18,
    denominator: 20,
    eligible_count: 20,
    missing_count: 0,
    unavailable_reason: null,
    uncertainty: { method: 'wilson', level: 0.95, lower: 0.6989663547715129, upper: 0.9721335187862318, label: '95% Wilson interval (frequentist)', note: '' },
    contributing_trial_ids: ['t-1', 't-2'],
    contributing_case_ids: [],
    provenance: { formula: 'P / (P + F)', source: 'D' },
    ...overrides,
  }
}

export function trialDetail(overrides: Partial<TrialDetail> = {}): TrialDetail {
  return {
    id: 'trial-1',
    run_id: 'run-1',
    case_id: 'case-1',
    external_id: 'M05',
    severity: 'critical',
    cluster_id: 'c-5',
    tags: {},
    candidate_key: 'candidate',
    repeat_index: 0,
    status: 'success',
    latency_ms: 1,
    error_code: null,
    outcome: 'fail',
    outcome_reason: 'mandatory grader failed',
    invariant_failures: [],
    case: {
      id: 'case-1',
      dataset_id: 'ds-1',
      ordinal: 0,
      external_id: 'M05',
      purpose: 'Negation',
      input: {},
      episode: [],
      expected: { answer_contains: ['not'] },
      alternatives: [],
      evidence: [],
      tags: {},
      severity: 'critical',
      cluster_id: 'c-5',
      weight: 1,
      split: 'test',
      fixture_options: {},
      case_hash: 'h',
    },
    scenario_contract: { id: 'sc-1', hash: 'h', name: 'memoryai-lifecycle', pack: 'memory_lifecycle', version: 1 },
    is_demo: true,
    output: { text: 'You live in Melbourne.' },
    steps: [],
    output_artifacts: [],
    state_artifacts: [],
    error: null,
    selected_attempt_id: null,
    started_at: null,
    finished_at: null,
    attempts: [],
    grades: [],
    outcomes: [],
    siblings: [],
    ...overrides,
  }
}
